### ISSUE TITLE
windows : Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by spiritguide7** [AngularClass/angular2-seed#10]
[WDS] Warnings while compiling.
client?5713:42 ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
28:15 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at SystemImportContextDependency.getWarnings (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\dependencies\SystemImportContextDependency.js:23:4)
    at C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:634:21
    at Array.forEach (native)
    at C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:633:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:632:9)
    at Compilation.<anonymous> (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:491:8)
    at Array.forEach (native)
    at Compilation.finish (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:490:15)
    at Compiler.<anonymous> (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compiler.js:434:15)
client?5713:42 ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
37:15 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at SystemImportContextDependency.getWarnings (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\dependencies\SystemImportContextDependency.js:23:4)
    at C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:634:21
    at Array.forEach (native)
    at C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:633:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:632:9)
    at Compilation.<anonymous> (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:491:8)
    at Array.forEach (native)
    at Compilation.finish (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:490:15)
    at Compiler.<anonymous> (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compiler.js:434:15)
client?5713:42 ./~/@angular/core/src/linker/systemjs_component_resolver.js
28:19 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at SystemImportContextDependency.getWarnings (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\dependencies\SystemImportContextDependency.js:23:4)
    at C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:634:21
    at Array.forEach (native)
    at C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:633:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:632:9)
    at Compilation.<anonymous> (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:491:8)
    at Array.forEach (native)
    at Compilation.finish (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:490:15)
    at Compiler.<anonymous> (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compiler.js:434:15)
client?5713:42 ./~/@angular/core/src/linker/systemjs_component_resolver.js
56:19 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at SystemImportContextDependency.getWarnings (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\dependencies\SystemImportContextDependency.js:23:4)
    at C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:634:21
    at Array.forEach (native)
    at C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:633:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:632:9)
    at Compilation.<anonymous> (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:491:8)
    at Array.forEach (native)
    at Compilation.finish (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compilation.js:490:15)
    at Compiler.<anonymous> (C:\Users\Jack\Documents\ang2\angular2-seed-master\node_modules\webpack\lib\Compiler.js:434:15)

**Comment by Meligy** [comment]
I think I'm seeing this as well.

> OS: Windows 10 x64
> Node: v6.2.2
> NPM: 3.9.5

At the end of webpack output I see

```
WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
28:15 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
37:15 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/src/linker/systemjs_component_resolver.js
28:19 Critical dependency: the request of a dependency is an expression

WARNING in ./~/@angular/core/src/linker/systemjs_component_resolver.js
56:19 Critical dependency: the request of a dependency is an expression
webpack: bundle is now VALID.
[default] Checking started in a separate process...
[default] Ok, 1.967 sec.
```

In the browser console I see:

```
Hello Angular 2 Webpack 2
Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.
Home
[WDS] Warnings while compiling.
./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
28:15 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at SystemImportContextDependency.getWarnings (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\dependencies\SystemImportContextDependency.js:23:4)
    at C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:634:21
    at Array.forEach (native)
    at C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:633:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:632:9)
    at Compilation.<anonymous> (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:491:8)
    at Array.forEach (native)
    at Compilation.finish (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:490:15)
    at Compiler.<anonymous> (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compiler.js:434:15)
./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
37:15 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at SystemImportContextDependency.getWarnings (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\dependencies\SystemImportContextDependency.js:23:4)
    at C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:634:21
    at Array.forEach (native)
    at C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:633:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:632:9)
    at Compilation.<anonymous> (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:491:8)
    at Array.forEach (native)
    at Compilation.finish (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:490:15)
    at Compiler.<anonymous> (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compiler.js:434:15)
./~/@angular/core/src/linker/systemjs_component_resolver.js
28:19 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at SystemImportContextDependency.getWarnings (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\dependencies\SystemImportContextDependency.js:23:4)
    at C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:634:21
    at Array.forEach (native)
    at C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:633:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:632:9)
    at Compilation.<anonymous> (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:491:8)
    at Array.forEach (native)
    at Compilation.finish (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:490:15)
    at Compiler.<anonymous> (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compiler.js:434:15)
./~/@angular/core/src/linker/systemjs_component_resolver.js
56:19 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at SystemImportContextDependency.getWarnings (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\dependencies\SystemImportContextDependency.js:23:4)
    at C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:634:21
    at Array.forEach (native)
    at C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:633:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:632:9)
    at Compilation.<anonymous> (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:491:8)
    at Array.forEach (native)
    at Compilation.finish (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compilation.js:490:15)
    at Compiler.<anonymous> (C:\Users\Meligy\Code\github\AngularClass\angular2-seed\node_modules\webpack\lib\Compiler.js:434:15)
```

The obvious problem is the `./~/` at the beginning of the `./~/@angular/core/src/linker/systemjs_*.js` files paths.

**Comment by Luke265** [comment]
Related with #7

**Comment by gdi2290** [comment]
closed via https://github.com/AngularClass/angular2-seed/pull/14
