### ISSUE TITLE
TypeError: Cannot read property 'js' of undefined

### ISSUE THREAD

**Issue by mmrath** [AngularClass/angular2-seed#20]
TypeError: Cannot read property 'js' of undefined
    at getDllAssets (C:\Projects\angular2-seed\webpack.config.ts:172:23)
    at C:\Projects\angular2-seed\webpack.config.ts:128:42
    at Layer.handle [as handle_request] (C:\Projects\angular2-seed\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Projects\angular2-seed\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Projects\angular2-seed\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Projects\angular2-seed\node_modules\express\lib\router\layer.js:95:5)
    at C:\Projects\angular2-seed\node_modules\express\lib\router\index.js:277:22
    at param (C:\Projects\angular2-seed\node_modules\express\lib\router\index.js:349:14)
    at param (C:\Projects\angular2-seed\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Projects\angular2-seed\node_modules\express\lib\router\index.js:410:3)

**Comment by gdi2290** [comment]
what does your dist/dll files look like. it's trying to require the webpack-assets.json file there

**Comment by mmrath** [comment]
There is webpack-assets.json with the following content. Looks like `assets[chunk]['js']` instead of  `assets[chunk].js` works. not 100% sure though. may be just TS typing problem.

`{
  "vendors": {
    "js": "vendors.d2058bf39f117c71a374.js"
  },
  "polyfills": {
    "js": "polyfills.d2058bf39f117c71a374.js"
  }
}`

**Comment by gdi2290** [comment]
ok I updated it
https://github.com/AngularClass/angular2-seed/commit/e789a32d50e9ae107d1fd4ced770e629667b2b9a
