### ISSUE TITLE
TypeError: Cannot read property 'js' of undefined

### ISSUE THREAD

**Issue by railsr** [AngularClass/angular2-seed#25]
Hi, I got the following error after `npm start`. 
It looks like it's complaining about the following line, beginning from `getDllAssets`

`res.sendFile(root('dist/dll/'+ getDllAssets(chunk)));`

But if I open localhost:3000, it works just fine.

```
TypeError: Cannot read property 'js' of undefined
    at getDllAssets (/Users/kirill/Desktop/ads/public/ng2-client/webpack.config.ts:172:23)
    at /Users/kirill/Desktop/ads/public/ng2-client/webpack.config.ts:128:42
    at Layer.handle [as handle_request] (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/index.js:277:22
    at param (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/index.js:410:3)

same output 3 times ....

[default] Checking started in a separate process...
TypeError: Cannot read property 'js' of undefined
    at getDllAssets (/Users/kirill/Desktop/ads/public/ng2-client/webpack.config.ts:172:23)
    at /Users/kirill/Desktop/ads/public/ng2-client/webpack.config.ts:128:42
    at Layer.handle [as handle_request] (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/layer.js:95:5)
    at /Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/index.js:277:22
    at param (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/index.js:349:14)
    at param (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/kirill/Desktop/ads/public/ng2-client/node_modules/express/lib/router/index.js:410:3)
[default] Ok, 2.388 sec.

```

**Comment by railsr** [comment]
after running `npm start` again the problem disapperared
