### ISSUE TITLE
[Windows] Cannot find module './+about'

### ISSUE THREAD

**Issue by j3ddesign** [AngularClass/angular2-seed#7]
When clicking to the about route, I'm given the following error.
`EXCEPTION: Error: Uncaught (in promise): Error: Cannot find module './+about'.`

 I've tried adjust the path, and pointing directly at ./+about/index.js (& .ts) to no success.

Could this be related to the sheer mass of warnings I'm seeing in webpack & chrome: 
````
WARNING in ./~/@angular/core/src/linker/system_js_ng_module_factory_loader.js
28:15 
Critical dependency: the request of a dependency is an expression
```

**Comment by CalvinDale** [comment]
I'm encountering this issue as well. But I didn't see the _critical dependency_ warnings and the _about_ navigation exception in the related `angular2-webpack-starter` project.

**Comment by Luke265** [comment]
Here is the full warning:
````
11:03:34.608 ./~/@angular/core/src/linker/systemjs_component_resolver.js
56:19 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at SystemImportContextDependency.getWarnings (node_modules\webpack\lib\dependencies\SystemImportContextDependency.js:23:4)
    at node_modules\webpack\lib\Compilation.js:634:21
    at Array.forEach (native)
    at node_modules\webpack\lib\Compilation.js:633:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (node_modules\webpack\lib\Compilation.js:632:9)
    at Compilation.<anonymous> (node_modules\webpack\lib\Compilation.js:491:8)
    at Array.forEach (native)
    at Compilation.finish (node_modules\webpack\lib\Compilation.js:490:15)
    at Compiler.<anonymous> (node_modules\webpack\lib\Compiler.js:434:15)1 polyfills.bundle.js:3691:4
````

**Comment by Meligy** [comment]
That's perfect, @Luke265 :)

I tried your last option, works nicely on Windows and Mac. Added as a PR.

Thanks!

**Comment by j3ddesign** [comment]
Nice, that solution worked great @Luke265 , thanks a lot.
Thanks for adding that PR @Meligy - here's hoping it gets merged soon
