### ISSUE TITLE
ngrx-store-log-monitor: The pipe 'async' could not be found

### ISSUE THREAD

**Issue by lucianlature** [AngularClass/angular2-seed#8]
Hi!

I am trying to use the `ngrx-store-log-monitor`, but I get:

```
The pipe 'async' could not be found ("
    <div class="button-bar">
      <log-monitor-button (action)="handleReset()" [ERROR ->][disabled]="canReset$ | async">
        Reset
      </log-monitor-button>
"): LogMonitorComponent@2:51
**The pipe 'async' could not be found** ("
      </log-monitor-button>

      <log-monitor-button (action)="handleSweep()" [ERROR ->][disabled]="canSweep$ | async">
        Sweep
      </log-monitor-button>
"): LogMonitorComponent@10:51
**The pipe 'async' could not be found** ("
      </log-monitor-button>

      <log-monitor-button (action)="handleCommit()" [ERROR ->][disabled]="canCommit$ | async">
        Commit
      </log-monitor-button>
"): LogMonitorComponent@14:52
**The pipe 'async' could not be found** ("
    <div class="elements">
      <log-monitor-entry
        [ERROR ->]*ngFor="let item of (items$ | async); let i = index"
        [item]="item"
        [disabled]="i === "): LogMonitorComponent@20:8
Can't bind to 'ngForOf' since it isn't a known property of 'log-monitor-entry'.
1. If 'log-monitor-entry' is an Angular component and it has 'ngForOf' input, then verify that it is part of this module.
2. If 'log-monitor-entry' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
 ("
    <div class="elements">
      <log-monitor-entry
        [ERROR ->]*ngFor="let item of (items$ | async); let i = index"
        [item]="item"
        [disabled]="i === "): LogMonitorComponent@20:8
Property binding ngForOf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("
    </div>
    <div class="elements">
      [ERROR ->]<log-monitor-entry
        *ngFor="let item of (items$ | async); let i = index"
        [item]="item""): LogMonitorComponent@19:6 ; Zone: <root> ; Task: Promise.then ; Value: BaseException {message: "Template parse errors:↵The pipe 'async' could not …        [item]="item""): LogMonitorComponent@19:6", stack: "Error: Template parse errors:↵The pipe 'async' cou…tp://localhost:3000/polyfills.bundle.js:16393:38)"}message: "Template parse errors:↵The pipe 'async' could not be found ("↵    <div class="button-bar">↵      <log-monitor-button (action)="handleReset()" [ERROR ->][disabled]="canReset$ | async">↵        Reset↵      </log-monitor-button>↵"): LogMonitorComponent@2:51↵The pipe 'async' could not be found ("↵      </log-monitor-button>↵↵      <log-monitor-button (action)="handleSweep()" [ERROR ->][disabled]="canSweep$ | async">↵        Sweep↵      </log-monitor-button>↵"): LogMonitorComponent@10:51↵The pipe 'async' could not be found ("↵      </log-monitor-button>↵↵      <log-monitor-button (action)="handleCommit()" [ERROR ->][disabled]="canCommit$ | async">↵        Commit↵      </log-monitor-button>↵"): LogMonitorComponent@14:52↵The pipe 'async' could not be found ("↵    <div class="elements">↵      <log-monitor-entry↵        [ERROR ->]*ngFor="let item of (items$ | async); let i = index"↵        [item]="item"↵        [disabled]="i === "): LogMonitorComponent@20:8↵Can't bind to 'ngForOf' since it isn't a known property of 'log-monitor-entry'.↵1. If 'log-monitor-entry' is an Angular component and it has 'ngForOf' input, then verify that it is part of this module.↵2. If 'log-monitor-entry' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.↵ ("↵    <div class="elements">↵      <log-monitor-entry↵        [ERROR ->]*ngFor="let item of (items$ | async); let i = index"↵        [item]="item"↵        [disabled]="i === "): LogMonitorComponent@20:8↵Property binding ngForOf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("↵    </div>↵    <div class="elements">↵      [ERROR ->]<log-monitor-entry↵        *ngFor="let item of (items$ | async); let i = index"↵        [item]="item""): LogMonitorComponent@19:6"stack: "Error: Template parse errors:↵The pipe 'async' could not be found ("↵    <div class="button-bar">↵      <log-monitor-button (action)="handleReset()" [ERROR ->][disabled]="canReset$ | async">↵        Reset↵      </log-monitor-button>↵"): LogMonitorComponent@2:51↵The pipe 'async' could not be found ("↵      </log-monitor-button>↵↵      <log-monitor-button (action)="handleSweep()" [ERROR ->][disabled]="canSweep$ | async">↵        Sweep↵      </log-monitor-button>↵"): LogMonitorComponent@10:51↵The pipe 'async' could not be found ("↵      </log-monitor-button>↵↵      <log-monitor-button (action)="handleCommit()" [ERROR ->][disabled]="canCommit$ | async">↵        Commit↵      </log-monitor-button>↵"): LogMonitorComponent@14:52↵The pipe 'async' could not be found ("↵    <div class="elements">↵      <log-monitor-entry↵        [ERROR ->]*ngFor="let item of (items$ | async); let i = index"↵        [item]="item"↵        [disabled]="i === "): LogMonitorComponent@20:8↵Can't bind to 'ngForOf' since it isn't a known property of 'log-monitor-entry'.↵1. If 'log-monitor-entry' is an Angular component and it has 'ngForOf' input, then verify that it is part of this module.↵2. If 'log-monitor-entry' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.↵ ("↵    <div class="elements">↵      <log-monitor-entry↵        [ERROR ->]*ngFor="let item of (items$ | async); let i = index"↵        [item]="item"↵        [disabled]="i === "): LogMonitorComponent@20:8↵Property binding ngForOf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("↵    </div>↵    <div class="elements">↵      [ERROR ->]<log-monitor-entry↵        *ngFor="let item of (items$ | async); let i = index"↵        [item]="item""): LogMonitorComponent@19:6↵    at new BaseException (http://localhost:3000/vendor.bundle.js:3412:23)↵    at TemplateParser.parse (http://localhost:3000/vendor.bundle.js:17110:19)↵    at RuntimeCompiler._compileTemplate (http://localhost:3000/vendor.bundle.js:37417:51)↵    at http://localhost:3000/vendor.bundle.js:37345:83↵    at Set.forEach (native)↵    at compile (http://localhost:3000/vendor.bundle.js:37345:47)↵    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:16360:29)↵    at Zone.run (http://localhost:3000/polyfills.bundle.js:16253:44)↵    at http://localhost:3000/polyfills.bundle.js:16608:58↵    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:16393:38)"__proto__: ErrorconsoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
```

**Comment by gdi2290** [comment]
for `ngrx-store-log-monitor` you need to es6-import all of their directives and place them into `declarations` in the correct order or create an `ngrx-store-log-monitor` NgModule that ng-imports and ng-exports their directives then es6-import that in your main app.
or
just ask everyone else to update their 3rd party modules to use NgModule so you can es6-import them in your ng-import

**Comment by MikeRyan52** [comment]
@lucianlature We are in the process of upgrading all ngrx projects to RC5. Probably only a few days out.
